name: youtube_music_browse
description: "A package to fetch data from youtube music"
version: 0.0.1
homepage: ''

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  copy_with_extension_gen: ^5.0.4
  build_runner: any

flutter:
